config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'pages/about'
  get 'pages/contact'
  root 'videos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord

  def next
    Video.where("id > ?", id).first
  end

  def prev
    Video.where("id < ?", id).last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
     @videos = Video.all
     @next_video = @video.next
     @prev_video = @video.prev

  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Code4Newbies</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                    <!-- Compiled and minified CSS -->
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

                    <!-- Compiled and minified JavaScript -->
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

                     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>

    <!-- THIS IS THE NAVBAR -->

    <nav>
    <div class="nav-wrapper">
      <%= link_to "Logo", root_path, :class => "brand-logo" %>
      <ul class="right">
        <li><a href="<%=pages_about_path%>"><i class="large material-icons">person</i></a></li>
       <li><a href="<%=pages_contact_path%>"><i class="large material-icons">location_on</i></a></li>
      </ul>
    </div>
  </nav>

    <!-- THIS IS FOR THE SCREEN -->

    <div class="row">
        <div class="col m10 offset-m1">
            <%= yield %>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, options);
        });

        // Or with jQuery

        $(document).ready(function() {
            $('.sidenav').sidenav();
        });
    </script>

</body>

</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<h3> About me <h3>

  <div class="card z-depth-3">
    <div class="card-content white-text">
          <div class="col m6">
          </div>
          <div class="col m6">
             <div class="card-panel grey lighten-5 z-depth-1">
               <div class="row valign-wrapper">
                  <div class="col m3">
                    <%=image_tag "avatar.jpg", class: "circle responsive-img" %>
                  </div>
                  <div class="col m9">
                    <span class ="black-text">
                    I don't know what to say
                    </span>
                  </div>
                </div>
              </div>
          </div>
    </div>
  </div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

<h3> Contact <h3>

<div class="card z-depth-3">
  <div class="card-content">
    <p> Do you wanna talk? </p>
    <br/>
    <div id="map-canvas"></div>
<style>
  #map-canvas {
    width: 100%;
    height: 400px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: new google.maps.LatLng(-37.81, 144.96),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions);
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(-37.81, 144.96),
      title: "Melbourne here!"
    });
    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.text_field :wistia, :placeholder => 'Link', :length => "10" %>
  </div>

  <div class="input-field">
    <%= form.text_field :title, :placeholder => 'Title', :length => "20" %>
  </div>

  <div class="-input field">
    <%= form.text_area :description, :placeholder => 'Description', :length => "800", :class => "materialize-textarea" %>
  </div>
  <button class ="btn waves-effect waves-light" type ="submit" name ="action"> Submit</button>
  <a href = "<%= videos_path%>" class =btn waves-effect waves-light">Back</a>

<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<div class="card-content">

<%= render 'form', video: @video %>

</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Wistia</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.wistia %></td>
        <td><%= video.title %></td>
        <td><%= video.description %></td>

        <!-- SHOW REGULAR GREEN BUTTON - MATERIALIZE -->
        <td><%= link_to 'Show', video, :class =>"btn waves-effect waves-light" %></td>

        <!-- EDIT ICON BUTTON MATERIALIZE -->
        <td><%= link_to edit_video_path(video) do %>
          <i class="material-icons">edit</i>
        <%end%>
        </td>
        <!-- DELETE ICON BUTTON  -->
        <td><%= link_to video, method: :delete, data: { confirm: 'Are you sure?'} do %>
        <i class="material-icons">delete</i>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card-content">

<%= render 'form', video: @video %>

</div>

app/views/videos/show.html.erb
<p id="notice">
    <%= notice %>
</p>

<div class="row">

    <div class="col m3">
    <div class="collection">

        <% @videos.each do |video| %>
            <%= link_to video.title, video, :class => 'collection-item' %>
                <% end %>

    </div>
    </div>

    <div class="col m9">

        <div class="row">
            <div class="col m10">
                <div class="card">
                    <div class="card-image">
                        <img src="https://images.unsplash.com/photo-1501159771943-cc9027db4d8b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=05daa85f6d47b2bac2ccfcaa9c55b2b9&auto=format&fit=crop&w=750&q=80">
                        <div class="card-action">
                            <h3><%=@video.title %>
                            </h3>
                            <p> <%= @video.description%></p>
                        </div>
                        <div class="card-action">
                            <%= link_to "Previous", @prev_video if !@prev_video.nil? %>
                            <span class="right">
                        <%= link_to "Next", @next_video if !@next_video.nil? %>
                        </div>
      </div>
    </div>
  </div>

</div>
</div>